# Fly.io configuration for CrashInsight
app = "crashinsight"
primary_region = "ord"

[build]

[env]
  FLASK_ENV = "production"
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

  [[http_service.machines]]
    memory = "2gb"
    cpu_kind = "shared"
    cpus = 1

[[vm]]
  memory = "2gb"
  cpu_kind = "shared"
  cpus = 1